### ISSUE TITLE
Status of Fuel Tanks, valves, selectors, fuel dump etc. 

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#10]
**What data would you like to see in Touch Portal that comes from your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Fuel_Variables.htm
		(FUELSYSTEM TANK LEVEL:index)		        Quantity of fuel available in the indexed fuel tank. The index is the number of the tank N component as defined by the Tank.             
		
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Fuel_Variables.htm#FUEL_TANK_SELECTOR
		FUEL TANK SELECTOR:index

		FUEL DUMP ACTIVE                     If 1 (TRUE) then the aircraft can dump fuel.

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Fuel_Variables.htm#FUEL_SELECTED_QUANTITY_PERCENT

		FUEL SELECTED QUANTITY PERCENT:index

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

FUEL

**Additional context**
Display current fuel level - Maybe even by fuel tank
Detect if fuel is running low in currently selected tank and give alert if so

**Comment by mpaperno** [comment]
Any Sim Var is now available on demand.
