### ISSUE TITLE
Magneto Status

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#12]
**What data would you like to see in Touch Portal that comes from your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Engine_Events.htm#magneto
				https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Engine_Variables.htm#RECIP_ENG_LEFT_MAGNETO
				https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Engine_Variables.htm#RECIP_ENG_RIGHT_MAGNETO

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

ENGINES

**Additional context**

There is the ability in the plugin to set which magneto to use but not to query which (if any) are being used.
Good for the purists who want to go through a cheklist when starting the engines

**Comment by mpaperno** [comment]
Any Sim Var is now available on demand.
