### ISSUE TITLE
Autothrottle Status

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#13]
**What data would you like to see in Touch Portal that comes from your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_System_Variables.htm#AUTOTHROTTLE%20ACTIVE

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_AutopilotAssistant_Variables.htm#AUTOPILOT%20THROTTLE%20ARM

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

AUTOPILOT

**Additional context**

Autothrottle can be armed/deployed but there is no status showing whether it is available or active

**Comment by mpaperno** [comment]
Any Sim Var is now available on demand.
