### ISSUE TITLE
Autopilot Flight Level Change

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#15]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_AutopilotAssistant_Variables.htm#AUTOPILOT%20FLIGHT%20LEVEL%20CHANGE

				AP_FLIGHT_LEVEL_CHANGE	 	 
				AP_FLIGHT_LEVEL_CHANGE_OFF	 	 
				AP_FLIGHT_LEVEL_CHANGE_ON

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Autopilot_Flight_Assist_Events.htm

Also needs associated status to display current AP Flight Level setting and current Flight Level

I guess this could be current Altitude ASL / 100 and rounded to 500 feet

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

AUTOPILOT

**Additional context**

**Comment by mpaperno** [comment]
All Sim Vars and Events can be customized as needed.
