### ISSUE TITLE
Set Barometric Pressure	

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#16]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Instrumentation_Events.htm
	BAROMETRIC	Syncs altimeter setting to sea level pressure, or 29.92 if above 18000 feet
	BAROMETRIC_STD_PRESSURE
	KOHLSMAN_INC	Increments altimeter setting	Shared Cockpit
	KOHLSMAN_DEC	Decrements altimeter setting	Shared Cockpit
	KOHLSMAN_SET	Sets altimeter setting (Millibars * 16)
	Current pressure setting status
	KOHLSMAN SETTING HG:index	The value for the given altimeter index in inches of mercury.	
	KOHLSMAN SETTING MB:index	The value for the given altimeter index in millibars.

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

FLIGHT INSTRUMENTS

**Additional context**
In order to set pressure in response to ATC request, and to switch between European and US systems

**Comment by mpaperno** [comment]
Any Event can now be activated directly by name, with optional numeric parameter.
