### ISSUE TITLE
Toggle ATC window and allow responses 0...9

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#17]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Instrumentation_Events.htm#atc

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

COMMUNICATION

**Additional context**
Currently sending keystrokes so the Sim has to be in focus

**Comment by mpaperno** [comment]
I have tried everything possible but AFAICT there is no working SimConnect event or even working Calculator Code to open the ATC menu in the game, besides key strokes.  The 1-9 selections work, but not opening the actual menu.

Shelved unless MS fixes it.  :(
