### ISSUE TITLE
Reverse Thrust

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#18]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

		https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Engine_Events.htm#throttle
		THROTTLE_REVERSE_THRUST_TOGGLE	 	 
		THROTTLE_REVERSE_THRUST_HOLD

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**
ENGINES

**Additional context**
Additional support for Turboprop (TBM 930)  and Jet aircraft

**Comment by mpaperno** [comment]
Any Event can now be activated directly by name, with optional numeric parameter.
