### ISSUE TITLE
Set COM1/2 as active radio

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#19]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Radio_Navigation_Events.htm
    COM1_TRANSMIT_SELECT | Selects COM 1 to transmit
    COM1_RECEIVE_SELECT
    COM2_TRANSMIT_SELECT | Selects COM 1 to transmit
    COM2_RECEIVE_SELECT

Status
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#COM%20RECEIVE
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#COM%20TRANSMIT
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#COM%20TEST

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

COMMUNICATIONS

**Additional context**
Useful when switching frequencies between tower, approach, controlled airspace etc.
Also enables pilot to listen to ATIS or approach frequency on one COM box whilst being 'active' on the other  
Currently requires key combination to be setup in the Sim and keystrokes to be sent from TP

**Comment by mpaperno** [comment]
Any Event can now be activated directly by name, with optional numeric parameter, and any Sim Var requested or set (if settable).
