### ISSUE TITLE
ADF tuning, on/off, compass rose setting etc.

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#20]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Radio_Navigation_Events.htm#ADF
ADF | Sequentially selects the ADF tuner digits for use with +/-. Follow by SELECT_2 for ADF 2. | 
ADF_100_DEC | Decrements ADF by 100 KHz | Shared Cockpit
ADF_10_DEC | Decrements ADF by 10 KHz | Shared Cockpit
ADF_1_DEC | Decrements ADF by 1 KHz | Shared Cockpit
ADF_100_INC | Increments ADF by 100 KHz | Shared Cockpit
ADF_10_INC | Increments ADF by 10 KHz | Shared Cockpit
ADF_1_INC | Increments ADF by 1 KHz

ADF_CARD_DEC | Decrements ADF card | Shared Cockpit
ADF_CARD_INC | Increments ADF card | Shared Cockpit
ADF_CARD_SET | Sets ADF card (0-360)

RADIO_ADF_IDENT_SET
RADIO_ADF_IDENT_TOGGLE

STATUS
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#ADF%20ACTIVE%20FREQUENCY

ADF ACTIVE FREQUENCY:index
ADF AVAILABLE
ADF CARD
ADF IDENT
ADF RADIAL MAG
ADF SIGNAL

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

COMMUNICATIONS

**Additional context**
Used for folks who want to fly/are taught to fly by instruments on steam gauges without GPS or in case of GPS failure

**Comment by mpaperno** [comment]
Any Event can now be activated directly by name, with optional numeric parameter. All Sim Vars are available on demand.
