### ISSUE TITLE
Transponder  XPNDR - set frequency & ident

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#21]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Radio_Navigation_Events.htm#Transponder

XPNDR_1000_DEC | Decrements first digit of transponder | Shared Cockpit
XPNDR_100_DEC | Decrements second digit of transponder | Shared Cockpit
XPNDR_10_DEC | Decrements third digit of transponder | Shared Cockpit
XPNDR_1_DEC | Decrements fourth digit of transponder | Shared Cockpit
XPNDR_1000_INC | Increments first digit of transponder | Shared Cockpit
XPNDR_100_INC | Increments second digit of transponder | Shared Cockpit
XPNDR_10_INC | Increments third digit of transponder | Shared Cockpit
XPNDR_1_INC | Increments fourth digit of transponder | Shared Cockpit
XPNDR_DEC_CARRY | Decrements fourth digit of transponder, and with carry. | Shared Cockpit
XPNDR_INC_CARRY | Increments fourth digit of transponder, and with carry
XPNDR_IDENT_SET | Set the transponder Ident on or off (can be used along with the simvar TRANSPONDER_IDENT). If set to on, it will switch off automatically after 18 seconds.
XPNDR_IDENT_TOGGLE | Toggle the transponder Ident from on to off or off to on (can be used along with the simvar TRANSPONDER_IDENT).

STATUS
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#TRANSPONDER_AVAILABLE

TRANSPONDER AVAILABLE	True if a transponder is available	Bool	
TRANSPONDER CODE	4-digit code	All aircraft (Index of 1 only).	BCO16	
TRANSPONDER IDENT	This can set the Ident transponder using the KEY_XPNDR_IDENT_SET, KEY_XPNDR_IDENT_TOGGLE, KEY_XPNDR_IDENT_ON or KEY_XPNDR_IDENT_OFF 
 When set to true, it will automatically turn false after 18 seconds.	Bool	
TRANSPONDER STATE	Transponder State	

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**
Please provide the category if you have it, otherwise I will attempt to categorize the best I can.

**Additional context**
Used when ATC request pilot sets SQUAWK frequency and Ident

**Comment by mpaperno** [comment]
All these can be added as needed.  I recommend a custom states file, or even using the included Generator program to generate custom entry.tp file for Touch Portal.
