### ISSUE TITLE
VOR OBS Setting for NAV1, NAV2  Increase, Decrease

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#22]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Radio_Navigation_Events.htm#vor
	VOR1_OBI_DEC	Decrements the VOR 1 OBS setting	Shared Cockpit
	VOR1_OBI_FAST_DEC	 	 
	VOR1_OBI_FAST_INC	 	 
	VOR1_OBI_INC	Increments the VOR 1 OBS setting
	VOR2_OBI_DEC	Decrements the VOR 1 OBS setting	Shared Cockpit
	VOR2_OBI_FAST_DEC	 	 
	VOR2_OBI_FAST_INC	 	 
	VOR2_OBI_INC	Increments the VOR 1 OBS setting

	VOR1_SET | Sets OBS 1 (0 to 360)
	VOR2_SET | Sets OBS 2 (0 to 360)
	
RADIO_VOR1_IDENT_SET | Sets VOR 1 ID (on/off) | Shared Cockpit
	RADIO_VOR1_IDENT_TOGGLE | Toggles VOR 1 ID | Shared Cockpit
	RADIO_VOR2_IDENT_SET | Sets VOR 2 ID (on/off) | Shared Cockpit
	RADIO_VOR2_IDENT_TOGGLE | Toggles VOR 2 ID

STATUS
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#NAV_OBS

	NAV AVAILABLE | Flag if Nav equipped on aircraft | Bool
	NAV CODES | Returns bit flags with the following meaning.
	NAV DME
	NAV HAS CLOSE DME | Flag if found a close station with a DME | Bool |  
	NAV HAS CLOSE LOCALIZER | Flag if found a close localizer station | Bool |  
	NAV HAS DME | Flag if tuned station has a DME | Bool |  
	NAV HAS GLIDE SLOPE | Flag if tuned station has a glideslope | Bool |  
	NAV HAS LOCALIZER | Flag if tuned station is a localizer | Bool |  
	NAV HAS NAV | Flag if Nav has signal | Bool
	NAV OBS

	NAV IDENT | ICAO code | String

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

COMMUNICATIONS

**Additional context**
Used for NAV VOR navigation - which is used is in many not GPS equipped aircraft as well as for GPS equipped aircraft

**Comment by mpaperno** [comment]
All Sim Vars and Events can be customized as needed.
