### ISSUE TITLE
Marker Ident toggle for NAV1, NAV2, ADF

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#23]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#markers

Event & Status

	MARKER AVAILABLE	True if Marker is available	Bool
	MARKER_SOUND_TOGGLE			Toggles marker beacon sound on/off
	RADIO_VOR1_IDENT_SET			Sets VOR 1 ID (on/off)
	RADIO_VOR2_IDENT_SET			Sets VOR 2 ID (on/off)
	MARKER BEACON STATE | Marker beacon state. | Enum:0 = None1 = Outer2 = Middle3 = Inner   

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

COMMUNICATIONS

**Additional context**
Used to notify pilot when flying over a marker beacon

**Comment by mpaperno** [comment]
Any Sim Var is now available on demand.
