### ISSUE TITLE
GPS Approach Type

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#24]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#GPS

Tells G1000 or other GPS system which type of Autopilot approach to use:
GPS OVERRIDDEN	When it is active, all sim GPS system updates are suspended. This must be set to TRUE to be able to correctly set to any other GPS SimVar.  	Bool
GPS APPROACH APPROACH TYPE	- Approach type	
TOGGLE_GPS_DRIVES_NAV1	Toggles between GPS and NAV 1 driving NAV 1 OBS display (and AP)		Enum: 0 = None, 1 = GPS, 2 = VOR, 3 = NDB, 4 = ILS, 5 = Localizer, 8 = VOR/ DME, 9 = NDB/ DME, 10 = RNAV, 11 = Backcourse

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

COMMUNICATIONS

**Additional context**
Needed so that GPS equipped aircraft can use NAV VOR navigation

**Comment by mpaperno** [comment]
All sim vars (and a lot more in v1.0) can be customized as needed.
