### ISSUE TITLE
Camera Views and movement

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#25]
**What action do you want to be able to perform from Touch Portal to interact with your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Camera_Variables.htm

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

CAMERAS

**Additional context**
Be able to set camera views without having to send Keystrokes - cockpit is the set of views I use at the moment, but page could be extended to use external or drone views at some time in future.

I realise that this could be quite a bit of work so probably lower priority than the other enhancements.

**Comment by mpaperno** [comment]
This is all available since v0.8 or so, custom sim vars can be added and sim var values can be set.
