### ISSUE TITLE
Autopilot Available - Reports available on all aircraft 

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#27]
**Describe the bug**
Value - ${value:MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAvailable} shows 1 whether or not aircraft has autopilot facility - i.e. Stock Cessna 152 does not have AP functionality but still reports as available

**Expected behavior**
Show 0 if autopilot is not available

**Plugin Version**
6.0

**Comment by mpaperno** [comment]
The variable we're using is correct as far as I can tell (`AUTOPILOT AVAILABLE`).  If there's a better indicator to use, that can be added, but I'm not aware of one.  Maybe a local variable... .(with v1.0...).
