### ISSUE TITLE
Cowl Flap Open / Closed toggle & increase/decrease only moves a very small amount

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#28]
**Describe the bug**
Cowl flap cannot be set to fully open of fully closed instead depends on increase / decrease which take a very long time to make a difference

**Expected behavior**
Cowl flaps to be able to be set fully open or fully closed

**Plugin Version**
6.0

Workaround - Repeat increase/decrease 15 times

**Comment by mpaperno** [comment]
Cowl flaps can now be set to a specific value (in just released v1.0.0.0-beta1).

Not much to be done about the "INCR/DECR" commands since those movement amounts are controlled by the simulator.
