### ISSUE TITLE
HubHop Data not updating properly

### ISSUE THREAD

**Issue by mpaperno** [mpaperno/MSFSTouchPortalPlugin#32]
Hi, I new to all this, looking in the "Trigger a Simulator Event from loaded HubHop data" I see that PMDG-DC-6 is supported but I don't see the PMDG 737. I know that there was/is a new SDK. Is this something that will be added or I not using it like it should?

Thanks

_Originally posted by @magicnorm in https://github.com/mpaperno/MSFSTouchPortalPlugin/discussions/31#discussioncomment-3140012_

**Comment by mpaperno** [comment]
Thanks for the report!

Turns out the database does update but the old version is still cached so no new data is showing up in the "Trigger from HubHop" action.  And the original database is from before the PMDG 737 was added, so it doesn't show up at all (which turns out is good since it helped spot this bug :).

**The workaround for now is to restart the plugin after updating the HubHop data.** 
- To restart, go to Touch Portal's _Settings -> Plug-ins -> MSFS Touch Portal Plugin_ and hit the "stop" button then the "start" button.
- To update data there is the _MSFS - Plugin -> Connect & Update_ action you can add to a button with the _Update HubHop Data_ choice.  _Or_ in the plugin's settings you can also enable automatic updates whenever the plugin starts.

I will of course address this for the next version.

-Max

**Comment by mpaperno** [comment]
> FYI, It worked using the the "MSFS - Plugin -> Connect & Update action", but does not with the "Enable automatic updates whenever the plugin starts".

Cool, good to know.  There might have been a timing conflict when it checks at startup vs. when the data is loaded into the HubHop Action selectors.  Getting that all sorted now.

Thanks!
- Max
(I like the dot ;-)

**Comment by magicnorm** [comment]
Max,
It is not working for me, I tried with a few commands, but nothing.
I don't know if it is possible for you to check if it works for you using the PMDG-B737-700? 

- Norman

**Comment by mpaperno** [comment]
> It is not working for me, I tried with a few commands, but nothing.
> I don't know if it is possible for you to check if it works for you using the PMDG-B737-700?

Hmm well.. I don't have that aircraft but other generic events work for me...  Which WASM module are you using?

**Comment by magicnorm** [comment]
I copied the wasimcommander-module in my community folder, so I suppose it is using it.
I also know that PMDG have a new SDK since the last PMDG 737 update. Could HubHop data be outdated?

**Comment by mpaperno** [comment]
Did you restart the sim after installing the module? It should show up in your content manager _and_ show as active, with logo and my name under it.  (sorry if that's a dumb question, have to ask).

> I also know that PMDG have a new SDK since the last PMDG 737 update. Could HubHop data be outdated?

That I know nothing about.  I would verify that the `Activate a Simulator Event From HubHop` action works by trying something generic and obvious first, like  _MS - Generic - Lights - LANDING_LIGHTS_TOGGLE_. If it works for that then the issue with any particular event/action is most likely due to an issue with the data (the calculator code), not the plugin.

**Comment by magicnorm** [comment]
I created a basic button but it is not working. Let me know if you see something strange?
I also added the log file.

- Norman

![Screen Shot 07-13-22 at 07 23 PM](https://user-images.githubusercontent.com/76628415/178854517-cfb8c7eb-dbeb-4c8d-a6d1-8dfb7f633c7d.JPG)

[log.txt](https://github.com/mpaperno/MSFSTouchPortalPlugin/files/9106733/log.txt)

**Comment by mpaperno** [comment]
Mmm, please start a new discussion, maybe in the Q&A section (it could help others down the line).  Unfortunately I can't move your comment there (only start a new Issue).  Or check out the msfs2020 room on TP Discord server if you're into that sorta thing.

Also the log is a good idea, though I'd be more interested in the plugin's log (README.md -> Troubleshooting). Though I doubt this has anything to do with the plugin itself (meaning I doubt there's anything of interest in the log).
