### ISSUE TITLE
Engine Power and ECAM Buttons not correct.

### ISSUE THREAD

**Issue by Pyrolator** [mpaperno/MSFSTouchPortalPlugin#57]
![PedestalEngineError](https://github.com/mpaperno/MSFSTouchPortalPlugin/assets/141125980/19d6d6cb-c4b2-439c-bccd-651e897254cc)

Hello Creators.
As you see in the attached Picture - the Value for the Engines are not shown.
Also the ECAM-Buttons dont work, except the "ALL" Button.

Please investigate how to correct this Error's

All neccesary Files and Modules are latest Versions.
FBW A320 Stable V0.10.1

For fixing this Issues an Sponsoring follows :)

BTW thanks for this great TouchPortal Modul

**Comment by mpaperno** [comment]
Hello,

This is some problem with the _page_ created by GoodSeb over at flightsim.to ([this one](https://flightsim.to/file/40431/touch-portal-pages-for-flybywire-a32nx), I presume).  This is not, apparently, an issue with this plugin itself (unless that can be demonstrated somehow directly).

Sorry I can't help further at this point, that's not a page or model I personally use.  Please ask GoodSeb for help (and if he can trace the issue to something to do with this plugin, I'm happy to take a look).

Best,
-Max

**Comment by Pyrolator** [comment]
Thx for the fast answer, i try to contact GoodSeb.

**Comment by mrussell1958** [comment]
The answer is to use this https://github.com/mpaperno/MSFSTouchPortalPlugin/releases/download/1.3.2.0/MSFS-TouchPortal-Plugin-1.3.2.0.tpp  The newer plugin isnt seeing all the FBW variables. I loaded this into touch portal and all works fine.

**Comment by Pyrolator** [comment]
Yeah, thx a lot, that fixes the missing Engine Values !
So its not a failure from the Pages. I hope Max read this lines and had the time to correct his TPP in a future Version.

ECAM Buttons maybe a error in the Page from GoodSeb, but its OK for now.

Thank you mrussell :)

greets from Germany
Roger

**Comment by mpaperno** [comment]
Could someone provide the list of variables affected?

I would like to see the actual .INI config file entries for them, please.

The big difference in plugin v1.4 is that Local vars are being requested via SimConnect now, not WASM.  As far as I know so far, all other Local vars work fine.  So we would need to know which vars/requests are affected specifically.

As always, plugin log files showing the issue (in v1.4) would also be appreciated.

Thanks,
-Max

**Comment by mpaperno** [comment]
It could also be related to this change in v1.4:

> Added some basic validation of variable request parameters when loading from .INI configuration files. Invalid requests are rejected. Validation errors and warnings are reported in the plugin's log.

So again, need to see the actual variables please, and ideally the corresponding log entries.

To  be clear, I'm talking about the plugin's log, not TP's.  As explained here: https://github.com/mpaperno/MSFSTouchPortalPlugin#troubleshooting

Thanks,
-Max

**Comment by Pyrolator** [comment]
OK, i send my 2 logfiles, V1.3.2 and V1.4.1
i hope they are the correct ones.

[1.3.2MSFSTouchPortalPlugin20230804.log](https://github.com/mpaperno/MSFSTouchPortalPlugin/files/12259127/1.3.2MSFSTouchPortalPlugin20230804.log)
[1.4.MSFSTouchPortalPlugin20230804.log](https://github.com/mpaperno/MSFSTouchPortalPlugin/files/12259128/1.4.MSFSTouchPortalPlugin20230804.log)

Greets from Germany

**Comment by mpaperno** [comment]
Hi Roger, perfect, thank you.  And thanks for the buck!  :)

The issues are what appear to be L vars with `:` in the names, like `A32NX_ENGINE_N1:1`.  I guess this is what @mrussell1958 was trying to tell me in the related discussion, but this proves it.

I didn't think this was allowed in L var names, but I could be wrong.  The question then is, are those the actual variable names the "FBW A320 Stable" uses?  I will try to check their SDK docs, but if someone with the model installed could check the L vars list that would be a big help (Dev mode -> Behaviors Inspector -> Local Variables).

Thanks again!
-Max

**Comment by mpaperno** [comment]
Answering myself... indeed the FBW API docs lists L vars with `:index` numbers in the names. So I guess these are legal names, and I will indeed need to fix the validation on the plugin side. Don't know why they chose this unusual syntax (it may backfire on them one day), but c'est la vie.

Thanks for the reports!
-Max

**Comment by mpaperno** [comment]
Should be fixed in [v1.4.2](https://github.com/mpaperno/MSFSTouchPortalPlugin/releases/tag/1.4.2.0)!
