### ISSUE TITLE
Is Landing Gear Available

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#6]
**What data would you like to see in Touch Portal that comes from your simulator/aircraft?**
Please provide the state name if you already know it, if not please make sure to be detailed about what you are wanting to accomplish. 

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Brake_Landing_Gear_Variables.htm#IS_GEAR_RETRACTABLE
SimVar - (IS GEAR RETRACTABLE)		True if gear can be retracted

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**
Please provide the category if you have it, otherwise I will attempt to categorize the best I can.

Flight Systems

**Additional context**

Useful to know if gear is fixed or retractable so that if fixed I do not attempt to raise the landing gear but can state 'Gear Fixed' instead

**Comment by mpaperno** [comment]
Any Sim vars can now be added via TP actions and/or by using custom config files.
