### ISSUE TITLE
Engine actual RPM rather than RPM %

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#8]
**What data would you like to see in Touch Portal that comes from your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Engine_Variables.htm#ENG%20MAX%20RPM
				  (ENG MAX RPM)	The indexed engine (see note) Maximum rpm.	RPM
				  (ENG N1 RPM:index)	The indexed engine (see note) N1 rpm.	(0 to 16384 = 0 to 100%)

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

ENGINE

**Additional context**

So that the Engine RPM readout can be switched between Actual RPM and % RPM

**Comment by mpaperno** [comment]
Any Sim Var is now available on demand.
