### ISSUE TITLE
Altitude ASL according to QNH rather than 29.92

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#9]
**What data would you like to see in Touch Portal that comes from your simulator/aircraft?**

https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_System_Variables.htm#INDICATED_ALTITUDE_CALIBRATED
SimVar - INDICATED ALTITUDE CALIBRATED	- Indicated altitude with the altimeter calibrated to current sea level pressure.

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**

FLIGHT INSTRUMENTS

**Additional context**

Altitude ASL is currently shown at standard temperatures and pressures rather than the current barometric pressure value.  The altitude hold value and altimeter in the sim are at current barometric pressures rather than 29.92 inMg

**Comment by mpaperno** [comment]
Any Sim Var is now available on demand.
